# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyWindow(object):
    def setupUi(self, MyWindow):
        MyWindow.setObjectName("MyWindow")
        MyWindow.resize(361, 588)
        self.centralwidget = QtWidgets.QWidget(MyWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 10, 341, 91))
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputLabel.setLineWidth(2)
        self.outputLabel.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.outputLabel.setObjectName("outputLabel")
        self.percentButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press_it("%")
        )
        self.percentButton.setGeometry(QtCore.QRect(10, 110, 75, 75))
        self.percentButton.setObjectName("percentButton")
        self.cButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press_it("C")
        )
        self.cButton.setGeometry(QtCore.QRect(100, 110, 75, 75))
        self.cButton.setObjectName("cButton")
        self.arrowButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.remove_it()
        )
        self.arrowButton.setGeometry(QtCore.QRect(190, 110, 75, 75))
        self.arrowButton.setObjectName("arrowButton")
        self.divideButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press_it("/")
        )
        self.divideButton.setGeometry(QtCore.QRect(280, 110, 75, 75))
        self.divideButton.setObjectName("divideButton")
        self.eightButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press_it("8")
        )
        self.eightButton.setGeometry(QtCore.QRect(100, 200, 75, 75))
        self.eightButton.setObjectName("eightButton")
        self.multiplyButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press_it("*")
        )
        self.multiplyButton.setGeometry(QtCore.QRect(280, 200, 75, 75))
        self.multiplyButton.setObjectName("multiplyButton")
        self.sevenButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press_it("7")
        )
        self.sevenButton.setGeometry(QtCore.QRect(10, 200, 75, 75))
        self.sevenButton.setObjectName("sevenButton")
        self.nineButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press_it("9")
        )
        self.nineButton.setGeometry(QtCore.QRect(190, 200, 75, 75))
        self.nineButton.setObjectName("nineButton")
        self.fiveButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press_it("5")
        )
        self.fiveButton.setGeometry(QtCore.QRect(100, 290, 75, 75))
        self.fiveButton.setObjectName("fiveButton")
        self.minusButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press_it("-")
        )
        self.minusButton.setGeometry(QtCore.QRect(280, 290, 75, 75))
        self.minusButton.setObjectName("minusButton")
        self.fourButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press_it("4")
        )
        self.fourButton.setGeometry(QtCore.QRect(10, 290, 75, 75))
        self.fourButton.setObjectName("fourButton")
        self.sixButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press_it("6")
        )
        self.sixButton.setGeometry(QtCore.QRect(190, 290, 75, 75))
        self.sixButton.setObjectName("sixButton")
        self.twoButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press_it("2")
        )
        self.twoButton.setGeometry(QtCore.QRect(100, 380, 75, 75))
        self.twoButton.setObjectName("twoButton")
        self.addButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press_it("+")
        )
        self.addButton.setGeometry(QtCore.QRect(280, 380, 75, 75))
        self.addButton.setObjectName("addButton")
        self.oneButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press_it("1")
        )
        self.oneButton.setGeometry(QtCore.QRect(10, 380, 75, 75))
        self.oneButton.setObjectName("oneButton")
        self.threeButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press_it("3")
        )
        self.threeButton.setGeometry(QtCore.QRect(190, 380, 75, 75))
        self.threeButton.setObjectName("threeButton")
        self.zeroButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.press_it("0")
        )
        self.zeroButton.setGeometry(QtCore.QRect(100, 470, 75, 75))
        self.zeroButton.setObjectName("zeroButton")
        self.equalButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.calculate()
        )
        self.equalButton.setGeometry(QtCore.QRect(280, 470, 75, 75))
        self.equalButton.setObjectName("equalButton")
        self.plusMinusButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.plus_minus()
        )
        self.plusMinusButton.setGeometry(QtCore.QRect(10, 470, 75, 75))
        self.plusMinusButton.setObjectName("plusMinusButton")
        self.decimalButton = QtWidgets.QPushButton(
            self.centralwidget, clicked=lambda: self.dot_it()
        )

        self.decimalButton.setGeometry(QtCore.QRect(190, 470, 75, 75))
        self.decimalButton.setObjectName("decimalButton")
        MyWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MyWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 361, 21))
        self.menubar.setObjectName("menubar")
        MyWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MyWindow)
        self.statusbar.setObjectName("statusbar")
        MyWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MyWindow)
        QtCore.QMetaObject.connectSlotsByName(MyWindow)
        
    def remove_it(self):
        screen = self.outputLabel.text()
        
        screen = screen[:-1]
        self.outputLabel.setText(screen)
        
    def plus_minus(self):
        screen = self.outputLabel.text()
        
        if "-" in screen:
            self.outputLabel.setText(screen.replace("-", ""))
        else:
            self.outputLabel.setText(f"-{screen}")
            
    def calculate(self):
        screen = self.outputLabel.text()
        
        try:
            answer = eval(screen)
            self.outputLabel.setText(str(answer))
        except:
            self.outputLabel.setText("ERROR")

          


    def dot_it(self):
        screen = self.outputLabel.text()
        
        if screen[-1] == ".":
            pass
        else:
            self.outputLabel.setText(f"{screen}.")

    def press_it(self, pressed):
        if pressed == "C":
            self.outputLabel.setText("0")
        else:
            if self.outputLabel.text() == "0":
                self.outputLabel.setText("")
            self.outputLabel.setText(f"{self.outputLabel.text()}{pressed}")

    def retranslateUi(self, MyWindow):
        _translate = QtCore.QCoreApplication.translate
        MyWindow.setWindowTitle(_translate("MyWindow", "Calculator"))
        self.outputLabel.setText(_translate("MyWindow", "0"))
        self.percentButton.setText(_translate("MyWindow", "%"))
        self.cButton.setText(_translate("MyWindow", "C"))
        self.arrowButton.setText(_translate("MyWindow", "<<"))
        self.divideButton.setText(_translate("MyWindow", "/"))
        self.eightButton.setText(_translate("MyWindow", "8"))
        self.multiplyButton.setText(_translate("MyWindow", "X"))
        self.sevenButton.setText(_translate("MyWindow", "7"))
        self.nineButton.setText(_translate("MyWindow", "9"))
        self.fiveButton.setText(_translate("MyWindow", "5"))
        self.minusButton.setText(_translate("MyWindow", "-"))
        self.fourButton.setText(_translate("MyWindow", "4"))
        self.sixButton.setText(_translate("MyWindow", "6"))
        self.twoButton.setText(_translate("MyWindow", "2"))
        self.addButton.setText(_translate("MyWindow", "+"))
        self.oneButton.setText(_translate("MyWindow", "1"))
        self.threeButton.setText(_translate("MyWindow", "3"))
        self.zeroButton.setText(_translate("MyWindow", "0"))
        self.equalButton.setText(_translate("MyWindow", "="))
        self.plusMinusButton.setText(_translate("MyWindow", "+/-"))
        self.decimalButton.setText(_translate("MyWindow", "."))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MyWindow = QtWidgets.QMainWindow()
    ui = Ui_MyWindow()
    ui.setupUi(MyWindow)
    MyWindow.show()
    sys.exit(app.exec_())
